#!/usr/bin/env php
<?php
require dirname(__FILE__)."/Setting/Command/Command.php";
require_once   dirname((__FILE__)."")."/app/core/AutoLoad.php";
//
//AutoLoad::load();

$Command = new Command($argv);
$Command->run();


?>